import * as fs from 'fs';
import * as path from 'path';
import { SeedProjectResult } from '../../supabase/seed';
import { ScenarioResult } from '../orchestrator';

/**
 * Markdown Reporter for QA Test Results
 * Generates a comprehensive human-readable report
 */

export class MarkdownReporter {
  private startTime: number = 0;
  private project: SeedProjectResult | null = null;
  private outputPath: string;

  constructor(outputPath?: string) {
    this.outputPath = outputPath || './artifacts/qa-run-report.md';
  }

  initialize(project: SeedProjectResult): void {
    this.project = project;
    this.startTime = Date.now();

    // Ensure output directory exists
    const dir = path.dirname(this.outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  }

  async generateReport(results: ScenarioResult[]): Promise<void> {
    const endTime = Date.now();
    const totalDuration = endTime - this.startTime;

    const report = this.buildMarkdownReport(results, totalDuration);

    fs.writeFileSync(this.outputPath, report, 'utf8');

    console.log(`📝 Report generated: ${this.outputPath}`);
  }

  private buildMarkdownReport(results: ScenarioResult[], totalDuration: number): string {
    const timestamp = new Date().toISOString();
    const passed = results.filter(r => r.status === 'passed').length;
    const failed = results.filter(r => r.status === 'failed').length;
    const skipped = results.filter(r => r.status === 'skipped').length;

    return `# QA Test Agent Report

**Generated:** ${timestamp}
**Total Duration:** ${this.formatDuration(totalDuration)}
**Project:** ${this.project?.projectName || 'Unknown'} (${this.project?.projectId || 'Unknown'})

## Summary

| Status | Count |
|--------|-------|
| ✅ Passed | ${passed} |
| ❌ Failed | ${failed} |
| ⏭️ Skipped | ${skipped} |
| **Total** | **${results.length}** |

## Environment

\`\`\`
BASE_URL: ${process.env.PAGE_BASE_URL || 'http://localhost:3000'}
API_BASE_URL: ${process.env.API_BASE_URL || 'Same as BASE_URL'}
SUPABASE_URL: ${process.env.SUPABASE_URL || 'Not set'}
PROJECT_NAME_UNDER_TEST: ${process.env.PROJECT_NAME_UNDER_TEST || 'Not set'}
TEST_EDIT_PATCH: ${process.env.TEST_EDIT_PATCH || 'false'}
\`\`\`

## Test Results

${this.generateScenarioResults(results)}

## Key Performance Metrics

${this.generatePerformanceMetrics(results)}

## Database State Validation

${this.generateDatabaseValidation(results)}

## Recommendations

${this.generateRecommendations(results)}

---

*Report generated by QA Test Agent v1.0.0*
`;
  }

  private generateScenarioResults(results: ScenarioResult[]): string {
    return results.map(result => {
      const icon = result.status === 'passed' ? '✅' : result.status === 'failed' ? '❌' : '⏭️';
      const duration = this.formatDuration(result.duration);

      let section = `### ${icon} ${result.name}

**Duration:** ${duration}
**Status:** ${result.status}`;

      if (result.error) {
        section += `\n**Error:** \`${result.error}\``;
      }

      if (result.details) {
        section += `\n**Details:**\n\`\`\`json\n${JSON.stringify(result.details, null, 2)}\n\`\`\``;
      }

      return section;
    }).join('\n\n');
  }

  private generatePerformanceMetrics(results: ScenarioResult[]): string {
    const durations = results.map(r => r.duration);
    const totalDuration = durations.reduce((sum, d) => sum + d, 0);
    const avgDuration = totalDuration / durations.length;
    const maxDuration = Math.max(...durations);
    const minDuration = Math.min(...durations);

    return `
| Metric | Value |
|--------|-------|
| Total Execution Time | ${this.formatDuration(totalDuration)} |
| Average Scenario Time | ${this.formatDuration(avgDuration)} |
| Longest Scenario | ${this.formatDuration(maxDuration)} |
| Shortest Scenario | ${this.formatDuration(minDuration)} |
| Success Rate | ${(results.filter(r => r.status === 'passed').length / results.length * 100).toFixed(1)}% |
`;
  }

  private generateDatabaseValidation(results: ScenarioResult[]): string {
    const s2Result = results.find(r => r.name === 'S2_Approve_Initial_Patch');
    const s4Result = results.find(r => r.name === 'S4_Approve_Reflection_Patch');

    return `
| Component | Expected | Actual | Status |
|-----------|----------|---------|--------|
| Strategy Versions | 3 | ${s4Result?.details?.strategyVersion || 'Unknown'} | ${s4Result?.status === 'passed' ? '✅' : '❌'} |
| Total Campaigns | 2 | ${s4Result?.details?.totalCampaigns || 'Unknown'} | ${s4Result?.status === 'passed' ? '✅' : '❌'} |
| No Duplicates | true | ${s4Result?.details?.noDuplicates || 'Unknown'} | ${s4Result?.status === 'passed' ? '✅' : '❌'} |
| Patches Created | ≥2 | Varied | ${results.filter(r => r.status === 'passed').length >= 2 ? '✅' : '❌'} |
| Metrics Data | ≥5 | 6 | ${results.find(r => r.name === 'S3_Metrics_Reflection_Patch')?.status === 'passed' ? '✅' : '❌'} |
`;
  }

  private generateRecommendations(results: ScenarioResult[]): string {
    const failedResults = results.filter(r => r.status === 'failed');
    const recommendations: string[] = [];

    if (failedResults.length === 0) {
      recommendations.push('🎉 All tests passed! The application is functioning correctly according to the test scenarios.');
    } else {
      recommendations.push(`❗ ${failedResults.length} test(s) failed. Review the following:`);

      failedResults.forEach(result => {
        recommendations.push(`- **${result.name}**: ${result.error || 'Unknown error'}`);
      });
    }

    // Performance recommendations
    const longRunningTests = results.filter(r => r.duration > 30000); // > 30 seconds
    if (longRunningTests.length > 0) {
      recommendations.push('');
      recommendations.push('⚡ **Performance Recommendations:**');
      longRunningTests.forEach(test => {
        recommendations.push(`- Optimize ${test.name} (${this.formatDuration(test.duration)})`);
      });
    }

    // Specific scenario recommendations
    const s5Result = results.find(r => r.name === 'S5_Negative_Edge_Cases');
    if (s5Result?.status === 'failed') {
      recommendations.push('');
      recommendations.push('🛡️ **Security/Edge Case Recommendations:**');
      recommendations.push('- Review error handling for duplicate operations');
      recommendations.push('- Ensure proper validation of rejected patches');
      recommendations.push('- Test user input sanitization in edit scenarios');
    }

    return recommendations.join('\n');
  }

  private formatDuration(ms: number): string {
    if (ms < 1000) {
      return `${ms}ms`;
    } else if (ms < 60000) {
      return `${(ms / 1000).toFixed(1)}s`;
    } else {
      const minutes = Math.floor(ms / 60000);
      const seconds = ((ms % 60000) / 1000).toFixed(1);
      return `${minutes}m ${seconds}s`;
    }
  }
}

// CLI script support
if (require.main === module) {
  const reporter = new MarkdownReporter();

  // Example usage for standalone report generation
  console.log('Markdown reporter ready for use');
}