[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && chmod +x start.sh"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"